### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by vietwow** [linkedin/fossor#7] opened 2017-12-27 15:45 UTC
Hi all,

I think it's better if we have a Dockerfile for Fossor ;) Thanks.

Best Regards,

**Comment by scallister** [comment] 2017-12-27 16:29
Could you go into more detail? Is your intention to run an isolated instance of Fossor inside of its own docker container?

**Comment by vietwow** [comment] 2017-12-27 17:14
Ya, if we have docker image of Fossor, we don't need to install dependency (using yum or apt), just run "docker run ..."

Best Regards,

**Comment by scallister** [comment] 2017-12-27 18:04
That sounds helpful. I'm open to a pull request if you (or someone else) is up for adding that.

**Comment by scallister** [comment] 2018-01-11 18:28
We've discussed internally and I don't think docker is a good fit for Fossor's model. The issue is Fossor relies on being able to access many parts of the system. In order to maintain that functionality we would have to maintain an updated list of mount points in the docker file. I'm going to close this issue out for now.

**Closed as completed by scallister** 2018-01-11 18:28 UTC
Labels: enhancement, wontfix
